FROM registry.cn-hangzhou.aliyuncs.com/yiidii-hub/nginx-jre8:v1
MAINTAINER yd <3087233411@qq.com>
# envs
ENV BD_DIR=/bd

# 工作目录
WORKDIR ${BD_DIR}

# 后端
ADD ./back/target/BD-Share.jar ${BD_DIR}/app.jar
ADD ./back/docker/ ${BD_DIR}/

# 前端
RUN rm /etc/nginx/conf.d/default.conf
ADD default.conf /etc/nginx/conf.d/
ADD ./front/dist/ /usr/share/nginx/html/

# 其他操作
RUN mkdir -p ${BD_DIR}/logs/console

# 入口文件
ENTRYPOINT ["sh", "docker-entrypoint.sh"]

